services:
  scrumpoker:
    build:
      context: .
      args:
        BASE_PATH: /scrumpoker
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped

  apache:
    build: ./apache
    ports:
      - "80:80"
    depends_on:
      - scrumpoker
    restart: unless-stopped
